sonar.organization=rwell10-red
sonar.projectKey=rwell10-Red_roc-terraform-3tier-aws
sonar.sources=.
sonar.exclusions=.terraform/**,bootstrap/.terraform/**,.kiro/**
sonar.terraform.provider.aws.version=5.100.0
